<?php

/**
 * Base class that represents a row from the 'booksForSale' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 05/19/09 16:14:37
 *
 * @package    lib.model.om
 */
abstract class BaseBooksforsale extends BaseObject  implements Persistent {


  const PEER = 'BooksforsalePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        BooksforsalePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the isbn10 field.
	 * @var        string
	 */
	protected $isbn10;

	/**
	 * The value for the seller_id field.
	 * @var        int
	 */
	protected $seller_id;

	/**
	 * The value for the bookquality field.
	 * @var        int
	 */
	protected $bookquality;

	/**
	 * The value for the added_on field.
	 * @var        string
	 */
	protected $added_on;

	/**
	 * The value for the price field.
	 * @var        double
	 */
	protected $price;

	/**
	 * The value for the is_checked_out field.
	 * @var        string
	 */
	protected $is_checked_out;

	/**
	 * The value for the checked_out_by field.
	 * @var        int
	 */
	protected $checked_out_by;

	/**
	 * @var        Book
	 */
	protected $aBook;

	/**
	 * @var        User
	 */
	protected $aUserRelatedBySellerId;

	/**
	 * @var        User
	 */
	protected $aUserRelatedByCheckedOutBy;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseBooksforsale object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [isbn10] column value.
	 * 
	 * @return     string
	 */
	public function getIsbn10()
	{
		return $this->isbn10;
	}

	/**
	 * Get the [seller_id] column value.
	 * 
	 * @return     int
	 */
	public function getSellerId()
	{
		return $this->seller_id;
	}

	/**
	 * Get the [bookquality] column value.
	 * 
	 * @return     int
	 */
	public function getBookquality()
	{
		return $this->bookquality;
	}

	/**
	 * Get the [optionally formatted] temporal [added_on] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getAddedOn($format = 'Y-m-d H:i:s')
	{
		if ($this->added_on === null) {
			return null;
		}


		if ($this->added_on === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->added_on);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->added_on, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [price] column value.
	 * 
	 * @return     double
	 */
	public function getPrice()
	{
		return $this->price;
	}

	/**
	 * Get the [optionally formatted] temporal [is_checked_out] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getIsCheckedOut($format = 'Y-m-d H:i:s')
	{
		if ($this->is_checked_out === null) {
			return null;
		}


		if ($this->is_checked_out === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->is_checked_out);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->is_checked_out, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [checked_out_by] column value.
	 * 
	 * @return     int
	 */
	public function getCheckedOutBy()
	{
		return $this->checked_out_by;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Booksforsale The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = BooksforsalePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [isbn10] column.
	 * 
	 * @param      string $v new value
	 * @return     Booksforsale The current object (for fluent API support)
	 */
	public function setIsbn10($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->isbn10 !== $v) {
			$this->isbn10 = $v;
			$this->modifiedColumns[] = BooksforsalePeer::ISBN10;
		}

		if ($this->aBook !== null && $this->aBook->getIsbn10() !== $v) {
			$this->aBook = null;
		}

		return $this;
	} // setIsbn10()

	/**
	 * Set the value of [seller_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Booksforsale The current object (for fluent API support)
	 */
	public function setSellerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->seller_id !== $v) {
			$this->seller_id = $v;
			$this->modifiedColumns[] = BooksforsalePeer::SELLER_ID;
		}

		if ($this->aUserRelatedBySellerId !== null && $this->aUserRelatedBySellerId->getId() !== $v) {
			$this->aUserRelatedBySellerId = null;
		}

		return $this;
	} // setSellerId()

	/**
	 * Set the value of [bookquality] column.
	 * 
	 * @param      int $v new value
	 * @return     Booksforsale The current object (for fluent API support)
	 */
	public function setBookquality($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->bookquality !== $v) {
			$this->bookquality = $v;
			$this->modifiedColumns[] = BooksforsalePeer::BOOKQUALITY;
		}

		return $this;
	} // setBookquality()

	/**
	 * Sets the value of [added_on] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Booksforsale The current object (for fluent API support)
	 */
	public function setAddedOn($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->added_on !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->added_on !== null && $tmpDt = new DateTime($this->added_on)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->added_on = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = BooksforsalePeer::ADDED_ON;
			}
		} // if either are not null

		return $this;
	} // setAddedOn()

	/**
	 * Set the value of [price] column.
	 * 
	 * @param      double $v new value
	 * @return     Booksforsale The current object (for fluent API support)
	 */
	public function setPrice($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->price !== $v) {
			$this->price = $v;
			$this->modifiedColumns[] = BooksforsalePeer::PRICE;
		}

		return $this;
	} // setPrice()

	/**
	 * Sets the value of [is_checked_out] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Booksforsale The current object (for fluent API support)
	 */
	public function setIsCheckedOut($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->is_checked_out !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->is_checked_out !== null && $tmpDt = new DateTime($this->is_checked_out)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->is_checked_out = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = BooksforsalePeer::IS_CHECKED_OUT;
			}
		} // if either are not null

		return $this;
	} // setIsCheckedOut()

	/**
	 * Set the value of [checked_out_by] column.
	 * 
	 * @param      int $v new value
	 * @return     Booksforsale The current object (for fluent API support)
	 */
	public function setCheckedOutBy($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->checked_out_by !== $v) {
			$this->checked_out_by = $v;
			$this->modifiedColumns[] = BooksforsalePeer::CHECKED_OUT_BY;
		}

		if ($this->aUserRelatedByCheckedOutBy !== null && $this->aUserRelatedByCheckedOutBy->getId() !== $v) {
			$this->aUserRelatedByCheckedOutBy = null;
		}

		return $this;
	} // setCheckedOutBy()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->isbn10 = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->seller_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->bookquality = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->added_on = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->price = ($row[$startcol + 5] !== null) ? (double) $row[$startcol + 5] : null;
			$this->is_checked_out = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->checked_out_by = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = BooksforsalePeer::NUM_COLUMNS - BooksforsalePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Booksforsale object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aBook !== null && $this->isbn10 !== $this->aBook->getIsbn10()) {
			$this->aBook = null;
		}
		if ($this->aUserRelatedBySellerId !== null && $this->seller_id !== $this->aUserRelatedBySellerId->getId()) {
			$this->aUserRelatedBySellerId = null;
		}
		if ($this->aUserRelatedByCheckedOutBy !== null && $this->checked_out_by !== $this->aUserRelatedByCheckedOutBy->getId()) {
			$this->aUserRelatedByCheckedOutBy = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BooksforsalePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = BooksforsalePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aBook = null;
			$this->aUserRelatedBySellerId = null;
			$this->aUserRelatedByCheckedOutBy = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseBooksforsale:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BooksforsalePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			BooksforsalePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseBooksforsale:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseBooksforsale:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BooksforsalePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseBooksforsale:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			BooksforsalePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aBook !== null) {
				if ($this->aBook->isModified() || $this->aBook->isNew()) {
					$affectedRows += $this->aBook->save($con);
				}
				$this->setBook($this->aBook);
			}

			if ($this->aUserRelatedBySellerId !== null) {
				if ($this->aUserRelatedBySellerId->isModified() || $this->aUserRelatedBySellerId->isNew()) {
					$affectedRows += $this->aUserRelatedBySellerId->save($con);
				}
				$this->setUserRelatedBySellerId($this->aUserRelatedBySellerId);
			}

			if ($this->aUserRelatedByCheckedOutBy !== null) {
				if ($this->aUserRelatedByCheckedOutBy->isModified() || $this->aUserRelatedByCheckedOutBy->isNew()) {
					$affectedRows += $this->aUserRelatedByCheckedOutBy->save($con);
				}
				$this->setUserRelatedByCheckedOutBy($this->aUserRelatedByCheckedOutBy);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = BooksforsalePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = BooksforsalePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += BooksforsalePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aBook !== null) {
				if (!$this->aBook->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aBook->getValidationFailures());
				}
			}

			if ($this->aUserRelatedBySellerId !== null) {
				if (!$this->aUserRelatedBySellerId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUserRelatedBySellerId->getValidationFailures());
				}
			}

			if ($this->aUserRelatedByCheckedOutBy !== null) {
				if (!$this->aUserRelatedByCheckedOutBy->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUserRelatedByCheckedOutBy->getValidationFailures());
				}
			}


			if (($retval = BooksforsalePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = BooksforsalePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getIsbn10();
				break;
			case 2:
				return $this->getSellerId();
				break;
			case 3:
				return $this->getBookquality();
				break;
			case 4:
				return $this->getAddedOn();
				break;
			case 5:
				return $this->getPrice();
				break;
			case 6:
				return $this->getIsCheckedOut();
				break;
			case 7:
				return $this->getCheckedOutBy();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = BooksforsalePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getIsbn10(),
			$keys[2] => $this->getSellerId(),
			$keys[3] => $this->getBookquality(),
			$keys[4] => $this->getAddedOn(),
			$keys[5] => $this->getPrice(),
			$keys[6] => $this->getIsCheckedOut(),
			$keys[7] => $this->getCheckedOutBy(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = BooksforsalePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setIsbn10($value);
				break;
			case 2:
				$this->setSellerId($value);
				break;
			case 3:
				$this->setBookquality($value);
				break;
			case 4:
				$this->setAddedOn($value);
				break;
			case 5:
				$this->setPrice($value);
				break;
			case 6:
				$this->setIsCheckedOut($value);
				break;
			case 7:
				$this->setCheckedOutBy($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = BooksforsalePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIsbn10($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setSellerId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setBookquality($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAddedOn($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPrice($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setIsCheckedOut($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCheckedOutBy($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(BooksforsalePeer::DATABASE_NAME);

		if ($this->isColumnModified(BooksforsalePeer::ID)) $criteria->add(BooksforsalePeer::ID, $this->id);
		if ($this->isColumnModified(BooksforsalePeer::ISBN10)) $criteria->add(BooksforsalePeer::ISBN10, $this->isbn10);
		if ($this->isColumnModified(BooksforsalePeer::SELLER_ID)) $criteria->add(BooksforsalePeer::SELLER_ID, $this->seller_id);
		if ($this->isColumnModified(BooksforsalePeer::BOOKQUALITY)) $criteria->add(BooksforsalePeer::BOOKQUALITY, $this->bookquality);
		if ($this->isColumnModified(BooksforsalePeer::ADDED_ON)) $criteria->add(BooksforsalePeer::ADDED_ON, $this->added_on);
		if ($this->isColumnModified(BooksforsalePeer::PRICE)) $criteria->add(BooksforsalePeer::PRICE, $this->price);
		if ($this->isColumnModified(BooksforsalePeer::IS_CHECKED_OUT)) $criteria->add(BooksforsalePeer::IS_CHECKED_OUT, $this->is_checked_out);
		if ($this->isColumnModified(BooksforsalePeer::CHECKED_OUT_BY)) $criteria->add(BooksforsalePeer::CHECKED_OUT_BY, $this->checked_out_by);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(BooksforsalePeer::DATABASE_NAME);

		$criteria->add(BooksforsalePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Booksforsale (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIsbn10($this->isbn10);

		$copyObj->setSellerId($this->seller_id);

		$copyObj->setBookquality($this->bookquality);

		$copyObj->setAddedOn($this->added_on);

		$copyObj->setPrice($this->price);

		$copyObj->setIsCheckedOut($this->is_checked_out);

		$copyObj->setCheckedOutBy($this->checked_out_by);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Booksforsale Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     BooksforsalePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new BooksforsalePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Book object.
	 *
	 * @param      Book $v
	 * @return     Booksforsale The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setBook(Book $v = null)
	{
		if ($v === null) {
			$this->setIsbn10(NULL);
		} else {
			$this->setIsbn10($v->getIsbn10());
		}

		$this->aBook = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Book object, it will not be re-added.
		if ($v !== null) {
			$v->addBooksforsale($this);
		}

		return $this;
	}


	/**
	 * Get the associated Book object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Book The associated Book object.
	 * @throws     PropelException
	 */
	public function getBook(PropelPDO $con = null)
	{
		if ($this->aBook === null && (($this->isbn10 !== "" && $this->isbn10 !== null))) {
			$c = new Criteria(BookPeer::DATABASE_NAME);
			$c->add(BookPeer::ISBN10, $this->isbn10);
			$this->aBook = BookPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aBook->addBooksforsales($this);
			 */
		}
		return $this->aBook;
	}

	/**
	 * Declares an association between this object and a User object.
	 *
	 * @param      User $v
	 * @return     Booksforsale The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUserRelatedBySellerId(User $v = null)
	{
		if ($v === null) {
			$this->setSellerId(NULL);
		} else {
			$this->setSellerId($v->getId());
		}

		$this->aUserRelatedBySellerId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the User object, it will not be re-added.
		if ($v !== null) {
			$v->addBooksforsaleRelatedBySellerId($this);
		}

		return $this;
	}


	/**
	 * Get the associated User object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     User The associated User object.
	 * @throws     PropelException
	 */
	public function getUserRelatedBySellerId(PropelPDO $con = null)
	{
		if ($this->aUserRelatedBySellerId === null && ($this->seller_id !== null)) {
			$c = new Criteria(UserPeer::DATABASE_NAME);
			$c->add(UserPeer::ID, $this->seller_id);
			$this->aUserRelatedBySellerId = UserPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUserRelatedBySellerId->addBooksforsalesRelatedBySellerId($this);
			 */
		}
		return $this->aUserRelatedBySellerId;
	}

	/**
	 * Declares an association between this object and a User object.
	 *
	 * @param      User $v
	 * @return     Booksforsale The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUserRelatedByCheckedOutBy(User $v = null)
	{
		if ($v === null) {
			$this->setCheckedOutBy(NULL);
		} else {
			$this->setCheckedOutBy($v->getId());
		}

		$this->aUserRelatedByCheckedOutBy = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the User object, it will not be re-added.
		if ($v !== null) {
			$v->addBooksforsaleRelatedByCheckedOutBy($this);
		}

		return $this;
	}


	/**
	 * Get the associated User object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     User The associated User object.
	 * @throws     PropelException
	 */
	public function getUserRelatedByCheckedOutBy(PropelPDO $con = null)
	{
		if ($this->aUserRelatedByCheckedOutBy === null && ($this->checked_out_by !== null)) {
			$c = new Criteria(UserPeer::DATABASE_NAME);
			$c->add(UserPeer::ID, $this->checked_out_by);
			$this->aUserRelatedByCheckedOutBy = UserPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUserRelatedByCheckedOutBy->addBooksforsalesRelatedByCheckedOutBy($this);
			 */
		}
		return $this->aUserRelatedByCheckedOutBy;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aBook = null;
			$this->aUserRelatedBySellerId = null;
			$this->aUserRelatedByCheckedOutBy = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseBooksforsale:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseBooksforsale::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseBooksforsale
