<?php

/**
 * Base class that represents a row from the 'book' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 05/19/09 16:14:37
 *
 * @package    lib.model.om
 */
abstract class BaseBook extends BaseObject  implements Persistent {


  const PEER = 'BookPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        BookPeer
	 */
	protected static $peer;

	/**
	 * The value for the isbn10 field.
	 * @var        string
	 */
	protected $isbn10;

	/**
	 * The value for the isbn13 field.
	 * @var        string
	 */
	protected $isbn13;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the imagepath field.
	 * @var        string
	 */
	protected $imagepath;

	/**
	 * The value for the published field.
	 * @var        string
	 */
	protected $published;

	/**
	 * @var        array Author[] Collection to store aggregation of Author objects.
	 */
	protected $collAuthors;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAuthors.
	 */
	private $lastAuthorCriteria = null;

	/**
	 * @var        array Booksforsale[] Collection to store aggregation of Booksforsale objects.
	 */
	protected $collBooksforsales;

	/**
	 * @var        Criteria The criteria used to select the current contents of collBooksforsales.
	 */
	private $lastBooksforsaleCriteria = null;

	/**
	 * @var        array Comment[] Collection to store aggregation of Comment objects.
	 */
	protected $collComments;

	/**
	 * @var        Criteria The criteria used to select the current contents of collComments.
	 */
	private $lastCommentCriteria = null;

	/**
	 * @var        array Rating[] Collection to store aggregation of Rating objects.
	 */
	protected $collRatings;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRatings.
	 */
	private $lastRatingCriteria = null;

	/**
	 * @var        array Sales[] Collection to store aggregation of Sales objects.
	 */
	protected $collSaless;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSaless.
	 */
	private $lastSalesCriteria = null;

	/**
	 * @var        array Bookincategory[] Collection to store aggregation of Bookincategory objects.
	 */
	protected $collBookincategorys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collBookincategorys.
	 */
	private $lastBookincategoryCriteria = null;

	/**
	 * @var        array Wishlist[] Collection to store aggregation of Wishlist objects.
	 */
	protected $collWishlists;

	/**
	 * @var        Criteria The criteria used to select the current contents of collWishlists.
	 */
	private $lastWishlistCriteria = null;

	/**
	 * @var        array Courselitterature[] Collection to store aggregation of Courselitterature objects.
	 */
	protected $collCourselitteratures;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCourselitteratures.
	 */
	private $lastCourselitteratureCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseBook object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [isbn10] column value.
	 * 
	 * @return     string
	 */
	public function getIsbn10()
	{
		return $this->isbn10;
	}

	/**
	 * Get the [isbn13] column value.
	 * 
	 * @return     string
	 */
	public function getIsbn13()
	{
		return $this->isbn13;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [imagepath] column value.
	 * 
	 * @return     string
	 */
	public function getImagepath()
	{
		return $this->imagepath;
	}

	/**
	 * Get the [optionally formatted] temporal [published] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getPublished($format = 'Y-m-d H:i:s')
	{
		if ($this->published === null) {
			return null;
		}


		if ($this->published === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->published);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->published, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [isbn10] column.
	 * 
	 * @param      string $v new value
	 * @return     Book The current object (for fluent API support)
	 */
	public function setIsbn10($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->isbn10 !== $v) {
			$this->isbn10 = $v;
			$this->modifiedColumns[] = BookPeer::ISBN10;
		}

		return $this;
	} // setIsbn10()

	/**
	 * Set the value of [isbn13] column.
	 * 
	 * @param      string $v new value
	 * @return     Book The current object (for fluent API support)
	 */
	public function setIsbn13($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->isbn13 !== $v) {
			$this->isbn13 = $v;
			$this->modifiedColumns[] = BookPeer::ISBN13;
		}

		return $this;
	} // setIsbn13()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Book The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = BookPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Book The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = BookPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [imagepath] column.
	 * 
	 * @param      string $v new value
	 * @return     Book The current object (for fluent API support)
	 */
	public function setImagepath($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->imagepath !== $v) {
			$this->imagepath = $v;
			$this->modifiedColumns[] = BookPeer::IMAGEPATH;
		}

		return $this;
	} // setImagepath()

	/**
	 * Sets the value of [published] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Book The current object (for fluent API support)
	 */
	public function setPublished($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->published !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->published !== null && $tmpDt = new DateTime($this->published)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->published = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = BookPeer::PUBLISHED;
			}
		} // if either are not null

		return $this;
	} // setPublished()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->isbn10 = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->isbn13 = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->title = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->description = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->imagepath = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->published = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = BookPeer::NUM_COLUMNS - BookPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Book object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BookPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = BookPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collAuthors = null;
			$this->lastAuthorCriteria = null;

			$this->collBooksforsales = null;
			$this->lastBooksforsaleCriteria = null;

			$this->collComments = null;
			$this->lastCommentCriteria = null;

			$this->collRatings = null;
			$this->lastRatingCriteria = null;

			$this->collSaless = null;
			$this->lastSalesCriteria = null;

			$this->collBookincategorys = null;
			$this->lastBookincategoryCriteria = null;

			$this->collWishlists = null;
			$this->lastWishlistCriteria = null;

			$this->collCourselitteratures = null;
			$this->lastCourselitteratureCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseBook:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BookPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			BookPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseBook:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseBook:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BookPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseBook:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			BookPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = BookPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += BookPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAuthors !== null) {
				foreach ($this->collAuthors as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collBooksforsales !== null) {
				foreach ($this->collBooksforsales as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collComments !== null) {
				foreach ($this->collComments as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRatings !== null) {
				foreach ($this->collRatings as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSaless !== null) {
				foreach ($this->collSaless as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collBookincategorys !== null) {
				foreach ($this->collBookincategorys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collWishlists !== null) {
				foreach ($this->collWishlists as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCourselitteratures !== null) {
				foreach ($this->collCourselitteratures as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = BookPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAuthors !== null) {
					foreach ($this->collAuthors as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collBooksforsales !== null) {
					foreach ($this->collBooksforsales as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collComments !== null) {
					foreach ($this->collComments as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRatings !== null) {
					foreach ($this->collRatings as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSaless !== null) {
					foreach ($this->collSaless as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collBookincategorys !== null) {
					foreach ($this->collBookincategorys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collWishlists !== null) {
					foreach ($this->collWishlists as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCourselitteratures !== null) {
					foreach ($this->collCourselitteratures as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = BookPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIsbn10();
				break;
			case 1:
				return $this->getIsbn13();
				break;
			case 2:
				return $this->getTitle();
				break;
			case 3:
				return $this->getDescription();
				break;
			case 4:
				return $this->getImagepath();
				break;
			case 5:
				return $this->getPublished();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = BookPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIsbn10(),
			$keys[1] => $this->getIsbn13(),
			$keys[2] => $this->getTitle(),
			$keys[3] => $this->getDescription(),
			$keys[4] => $this->getImagepath(),
			$keys[5] => $this->getPublished(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = BookPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIsbn10($value);
				break;
			case 1:
				$this->setIsbn13($value);
				break;
			case 2:
				$this->setTitle($value);
				break;
			case 3:
				$this->setDescription($value);
				break;
			case 4:
				$this->setImagepath($value);
				break;
			case 5:
				$this->setPublished($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = BookPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIsbn10($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIsbn13($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTitle($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDescription($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setImagepath($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPublished($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(BookPeer::DATABASE_NAME);

		if ($this->isColumnModified(BookPeer::ISBN10)) $criteria->add(BookPeer::ISBN10, $this->isbn10);
		if ($this->isColumnModified(BookPeer::ISBN13)) $criteria->add(BookPeer::ISBN13, $this->isbn13);
		if ($this->isColumnModified(BookPeer::TITLE)) $criteria->add(BookPeer::TITLE, $this->title);
		if ($this->isColumnModified(BookPeer::DESCRIPTION)) $criteria->add(BookPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(BookPeer::IMAGEPATH)) $criteria->add(BookPeer::IMAGEPATH, $this->imagepath);
		if ($this->isColumnModified(BookPeer::PUBLISHED)) $criteria->add(BookPeer::PUBLISHED, $this->published);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(BookPeer::DATABASE_NAME);

		$criteria->add(BookPeer::ISBN10, $this->isbn10);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getIsbn10();
	}

	/**
	 * Generic method to set the primary key (isbn10 column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIsbn10($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Book (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIsbn10($this->isbn10);

		$copyObj->setIsbn13($this->isbn13);

		$copyObj->setTitle($this->title);

		$copyObj->setDescription($this->description);

		$copyObj->setImagepath($this->imagepath);

		$copyObj->setPublished($this->published);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAuthors() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAuthor($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getBooksforsales() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addBooksforsale($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getComments() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addComment($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRatings() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRating($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSaless() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSales($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getBookincategorys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addBookincategory($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getWishlists() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addWishlist($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCourselitteratures() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCourselitterature($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Book Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     BookPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new BookPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collAuthors collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAuthors()
	 */
	public function clearAuthors()
	{
		$this->collAuthors = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAuthors collection (array).
	 *
	 * By default this just sets the collAuthors collection to an empty array (like clearcollAuthors());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAuthors()
	{
		$this->collAuthors = array();
	}

	/**
	 * Gets an array of Author objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Book has previously been saved, it will retrieve
	 * related Authors from storage. If this Book is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Author[]
	 * @throws     PropelException
	 */
	public function getAuthors($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAuthors === null) {
			if ($this->isNew()) {
			   $this->collAuthors = array();
			} else {

				$criteria->add(AuthorPeer::ISBN10, $this->isbn10);

				AuthorPeer::addSelectColumns($criteria);
				$this->collAuthors = AuthorPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AuthorPeer::ISBN10, $this->isbn10);

				AuthorPeer::addSelectColumns($criteria);
				if (!isset($this->lastAuthorCriteria) || !$this->lastAuthorCriteria->equals($criteria)) {
					$this->collAuthors = AuthorPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAuthorCriteria = $criteria;
		return $this->collAuthors;
	}

	/**
	 * Returns the number of related Author objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Author objects.
	 * @throws     PropelException
	 */
	public function countAuthors(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAuthors === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AuthorPeer::ISBN10, $this->isbn10);

				$count = AuthorPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AuthorPeer::ISBN10, $this->isbn10);

				if (!isset($this->lastAuthorCriteria) || !$this->lastAuthorCriteria->equals($criteria)) {
					$count = AuthorPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAuthors);
				}
			} else {
				$count = count($this->collAuthors);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Author object to this object
	 * through the Author foreign key attribute.
	 *
	 * @param      Author $l Author
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAuthor(Author $l)
	{
		if ($this->collAuthors === null) {
			$this->initAuthors();
		}
		if (!in_array($l, $this->collAuthors, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAuthors, $l);
			$l->setBook($this);
		}
	}

	/**
	 * Clears out the collBooksforsales collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addBooksforsales()
	 */
	public function clearBooksforsales()
	{
		$this->collBooksforsales = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collBooksforsales collection (array).
	 *
	 * By default this just sets the collBooksforsales collection to an empty array (like clearcollBooksforsales());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initBooksforsales()
	{
		$this->collBooksforsales = array();
	}

	/**
	 * Gets an array of Booksforsale objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Book has previously been saved, it will retrieve
	 * related Booksforsales from storage. If this Book is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Booksforsale[]
	 * @throws     PropelException
	 */
	public function getBooksforsales($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBooksforsales === null) {
			if ($this->isNew()) {
			   $this->collBooksforsales = array();
			} else {

				$criteria->add(BooksforsalePeer::ISBN10, $this->isbn10);

				BooksforsalePeer::addSelectColumns($criteria);
				$this->collBooksforsales = BooksforsalePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(BooksforsalePeer::ISBN10, $this->isbn10);

				BooksforsalePeer::addSelectColumns($criteria);
				if (!isset($this->lastBooksforsaleCriteria) || !$this->lastBooksforsaleCriteria->equals($criteria)) {
					$this->collBooksforsales = BooksforsalePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastBooksforsaleCriteria = $criteria;
		return $this->collBooksforsales;
	}

	/**
	 * Returns the number of related Booksforsale objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Booksforsale objects.
	 * @throws     PropelException
	 */
	public function countBooksforsales(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collBooksforsales === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(BooksforsalePeer::ISBN10, $this->isbn10);

				$count = BooksforsalePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(BooksforsalePeer::ISBN10, $this->isbn10);

				if (!isset($this->lastBooksforsaleCriteria) || !$this->lastBooksforsaleCriteria->equals($criteria)) {
					$count = BooksforsalePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collBooksforsales);
				}
			} else {
				$count = count($this->collBooksforsales);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Booksforsale object to this object
	 * through the Booksforsale foreign key attribute.
	 *
	 * @param      Booksforsale $l Booksforsale
	 * @return     void
	 * @throws     PropelException
	 */
	public function addBooksforsale(Booksforsale $l)
	{
		if ($this->collBooksforsales === null) {
			$this->initBooksforsales();
		}
		if (!in_array($l, $this->collBooksforsales, true)) { // only add it if the **same** object is not already associated
			array_push($this->collBooksforsales, $l);
			$l->setBook($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Book is new, it will return
	 * an empty collection; or if this Book has previously
	 * been saved, it will retrieve related Booksforsales from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Book.
	 */
	public function getBooksforsalesJoinUserRelatedBySellerId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBooksforsales === null) {
			if ($this->isNew()) {
				$this->collBooksforsales = array();
			} else {

				$criteria->add(BooksforsalePeer::ISBN10, $this->isbn10);

				$this->collBooksforsales = BooksforsalePeer::doSelectJoinUserRelatedBySellerId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(BooksforsalePeer::ISBN10, $this->isbn10);

			if (!isset($this->lastBooksforsaleCriteria) || !$this->lastBooksforsaleCriteria->equals($criteria)) {
				$this->collBooksforsales = BooksforsalePeer::doSelectJoinUserRelatedBySellerId($criteria, $con, $join_behavior);
			}
		}
		$this->lastBooksforsaleCriteria = $criteria;

		return $this->collBooksforsales;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Book is new, it will return
	 * an empty collection; or if this Book has previously
	 * been saved, it will retrieve related Booksforsales from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Book.
	 */
	public function getBooksforsalesJoinUserRelatedByCheckedOutBy($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBooksforsales === null) {
			if ($this->isNew()) {
				$this->collBooksforsales = array();
			} else {

				$criteria->add(BooksforsalePeer::ISBN10, $this->isbn10);

				$this->collBooksforsales = BooksforsalePeer::doSelectJoinUserRelatedByCheckedOutBy($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(BooksforsalePeer::ISBN10, $this->isbn10);

			if (!isset($this->lastBooksforsaleCriteria) || !$this->lastBooksforsaleCriteria->equals($criteria)) {
				$this->collBooksforsales = BooksforsalePeer::doSelectJoinUserRelatedByCheckedOutBy($criteria, $con, $join_behavior);
			}
		}
		$this->lastBooksforsaleCriteria = $criteria;

		return $this->collBooksforsales;
	}

	/**
	 * Clears out the collComments collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addComments()
	 */
	public function clearComments()
	{
		$this->collComments = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collComments collection (array).
	 *
	 * By default this just sets the collComments collection to an empty array (like clearcollComments());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initComments()
	{
		$this->collComments = array();
	}

	/**
	 * Gets an array of Comment objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Book has previously been saved, it will retrieve
	 * related Comments from storage. If this Book is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Comment[]
	 * @throws     PropelException
	 */
	public function getComments($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collComments === null) {
			if ($this->isNew()) {
			   $this->collComments = array();
			} else {

				$criteria->add(CommentPeer::ISBN10, $this->isbn10);

				CommentPeer::addSelectColumns($criteria);
				$this->collComments = CommentPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CommentPeer::ISBN10, $this->isbn10);

				CommentPeer::addSelectColumns($criteria);
				if (!isset($this->lastCommentCriteria) || !$this->lastCommentCriteria->equals($criteria)) {
					$this->collComments = CommentPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCommentCriteria = $criteria;
		return $this->collComments;
	}

	/**
	 * Returns the number of related Comment objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Comment objects.
	 * @throws     PropelException
	 */
	public function countComments(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collComments === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CommentPeer::ISBN10, $this->isbn10);

				$count = CommentPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CommentPeer::ISBN10, $this->isbn10);

				if (!isset($this->lastCommentCriteria) || !$this->lastCommentCriteria->equals($criteria)) {
					$count = CommentPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collComments);
				}
			} else {
				$count = count($this->collComments);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Comment object to this object
	 * through the Comment foreign key attribute.
	 *
	 * @param      Comment $l Comment
	 * @return     void
	 * @throws     PropelException
	 */
	public function addComment(Comment $l)
	{
		if ($this->collComments === null) {
			$this->initComments();
		}
		if (!in_array($l, $this->collComments, true)) { // only add it if the **same** object is not already associated
			array_push($this->collComments, $l);
			$l->setBook($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Book is new, it will return
	 * an empty collection; or if this Book has previously
	 * been saved, it will retrieve related Comments from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Book.
	 */
	public function getCommentsJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collComments === null) {
			if ($this->isNew()) {
				$this->collComments = array();
			} else {

				$criteria->add(CommentPeer::ISBN10, $this->isbn10);

				$this->collComments = CommentPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CommentPeer::ISBN10, $this->isbn10);

			if (!isset($this->lastCommentCriteria) || !$this->lastCommentCriteria->equals($criteria)) {
				$this->collComments = CommentPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastCommentCriteria = $criteria;

		return $this->collComments;
	}

	/**
	 * Clears out the collRatings collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRatings()
	 */
	public function clearRatings()
	{
		$this->collRatings = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRatings collection (array).
	 *
	 * By default this just sets the collRatings collection to an empty array (like clearcollRatings());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRatings()
	{
		$this->collRatings = array();
	}

	/**
	 * Gets an array of Rating objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Book has previously been saved, it will retrieve
	 * related Ratings from storage. If this Book is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Rating[]
	 * @throws     PropelException
	 */
	public function getRatings($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRatings === null) {
			if ($this->isNew()) {
			   $this->collRatings = array();
			} else {

				$criteria->add(RatingPeer::TYPE_ID, $this->isbn10);

				RatingPeer::addSelectColumns($criteria);
				$this->collRatings = RatingPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RatingPeer::TYPE_ID, $this->isbn10);

				RatingPeer::addSelectColumns($criteria);
				if (!isset($this->lastRatingCriteria) || !$this->lastRatingCriteria->equals($criteria)) {
					$this->collRatings = RatingPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRatingCriteria = $criteria;
		return $this->collRatings;
	}

	/**
	 * Returns the number of related Rating objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Rating objects.
	 * @throws     PropelException
	 */
	public function countRatings(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRatings === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RatingPeer::TYPE_ID, $this->isbn10);

				$count = RatingPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RatingPeer::TYPE_ID, $this->isbn10);

				if (!isset($this->lastRatingCriteria) || !$this->lastRatingCriteria->equals($criteria)) {
					$count = RatingPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRatings);
				}
			} else {
				$count = count($this->collRatings);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Rating object to this object
	 * through the Rating foreign key attribute.
	 *
	 * @param      Rating $l Rating
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRating(Rating $l)
	{
		if ($this->collRatings === null) {
			$this->initRatings();
		}
		if (!in_array($l, $this->collRatings, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRatings, $l);
			$l->setBook($this);
		}
	}

	/**
	 * Clears out the collSaless collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSaless()
	 */
	public function clearSaless()
	{
		$this->collSaless = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSaless collection (array).
	 *
	 * By default this just sets the collSaless collection to an empty array (like clearcollSaless());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSaless()
	{
		$this->collSaless = array();
	}

	/**
	 * Gets an array of Sales objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Book has previously been saved, it will retrieve
	 * related Saless from storage. If this Book is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Sales[]
	 * @throws     PropelException
	 */
	public function getSaless($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSaless === null) {
			if ($this->isNew()) {
			   $this->collSaless = array();
			} else {

				$criteria->add(SalesPeer::ISBN10, $this->isbn10);

				SalesPeer::addSelectColumns($criteria);
				$this->collSaless = SalesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SalesPeer::ISBN10, $this->isbn10);

				SalesPeer::addSelectColumns($criteria);
				if (!isset($this->lastSalesCriteria) || !$this->lastSalesCriteria->equals($criteria)) {
					$this->collSaless = SalesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSalesCriteria = $criteria;
		return $this->collSaless;
	}

	/**
	 * Returns the number of related Sales objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Sales objects.
	 * @throws     PropelException
	 */
	public function countSaless(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSaless === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SalesPeer::ISBN10, $this->isbn10);

				$count = SalesPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SalesPeer::ISBN10, $this->isbn10);

				if (!isset($this->lastSalesCriteria) || !$this->lastSalesCriteria->equals($criteria)) {
					$count = SalesPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collSaless);
				}
			} else {
				$count = count($this->collSaless);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Sales object to this object
	 * through the Sales foreign key attribute.
	 *
	 * @param      Sales $l Sales
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSales(Sales $l)
	{
		if ($this->collSaless === null) {
			$this->initSaless();
		}
		if (!in_array($l, $this->collSaless, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSaless, $l);
			$l->setBook($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Book is new, it will return
	 * an empty collection; or if this Book has previously
	 * been saved, it will retrieve related Saless from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Book.
	 */
	public function getSalessJoinUserRelatedByBuyerId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSaless === null) {
			if ($this->isNew()) {
				$this->collSaless = array();
			} else {

				$criteria->add(SalesPeer::ISBN10, $this->isbn10);

				$this->collSaless = SalesPeer::doSelectJoinUserRelatedByBuyerId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SalesPeer::ISBN10, $this->isbn10);

			if (!isset($this->lastSalesCriteria) || !$this->lastSalesCriteria->equals($criteria)) {
				$this->collSaless = SalesPeer::doSelectJoinUserRelatedByBuyerId($criteria, $con, $join_behavior);
			}
		}
		$this->lastSalesCriteria = $criteria;

		return $this->collSaless;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Book is new, it will return
	 * an empty collection; or if this Book has previously
	 * been saved, it will retrieve related Saless from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Book.
	 */
	public function getSalessJoinUserRelatedBySellerId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSaless === null) {
			if ($this->isNew()) {
				$this->collSaless = array();
			} else {

				$criteria->add(SalesPeer::ISBN10, $this->isbn10);

				$this->collSaless = SalesPeer::doSelectJoinUserRelatedBySellerId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SalesPeer::ISBN10, $this->isbn10);

			if (!isset($this->lastSalesCriteria) || !$this->lastSalesCriteria->equals($criteria)) {
				$this->collSaless = SalesPeer::doSelectJoinUserRelatedBySellerId($criteria, $con, $join_behavior);
			}
		}
		$this->lastSalesCriteria = $criteria;

		return $this->collSaless;
	}

	/**
	 * Clears out the collBookincategorys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addBookincategorys()
	 */
	public function clearBookincategorys()
	{
		$this->collBookincategorys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collBookincategorys collection (array).
	 *
	 * By default this just sets the collBookincategorys collection to an empty array (like clearcollBookincategorys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initBookincategorys()
	{
		$this->collBookincategorys = array();
	}

	/**
	 * Gets an array of Bookincategory objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Book has previously been saved, it will retrieve
	 * related Bookincategorys from storage. If this Book is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Bookincategory[]
	 * @throws     PropelException
	 */
	public function getBookincategorys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBookincategorys === null) {
			if ($this->isNew()) {
			   $this->collBookincategorys = array();
			} else {

				$criteria->add(BookincategoryPeer::ISBN10, $this->isbn10);

				BookincategoryPeer::addSelectColumns($criteria);
				$this->collBookincategorys = BookincategoryPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(BookincategoryPeer::ISBN10, $this->isbn10);

				BookincategoryPeer::addSelectColumns($criteria);
				if (!isset($this->lastBookincategoryCriteria) || !$this->lastBookincategoryCriteria->equals($criteria)) {
					$this->collBookincategorys = BookincategoryPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastBookincategoryCriteria = $criteria;
		return $this->collBookincategorys;
	}

	/**
	 * Returns the number of related Bookincategory objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Bookincategory objects.
	 * @throws     PropelException
	 */
	public function countBookincategorys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collBookincategorys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(BookincategoryPeer::ISBN10, $this->isbn10);

				$count = BookincategoryPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(BookincategoryPeer::ISBN10, $this->isbn10);

				if (!isset($this->lastBookincategoryCriteria) || !$this->lastBookincategoryCriteria->equals($criteria)) {
					$count = BookincategoryPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collBookincategorys);
				}
			} else {
				$count = count($this->collBookincategorys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Bookincategory object to this object
	 * through the Bookincategory foreign key attribute.
	 *
	 * @param      Bookincategory $l Bookincategory
	 * @return     void
	 * @throws     PropelException
	 */
	public function addBookincategory(Bookincategory $l)
	{
		if ($this->collBookincategorys === null) {
			$this->initBookincategorys();
		}
		if (!in_array($l, $this->collBookincategorys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collBookincategorys, $l);
			$l->setBook($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Book is new, it will return
	 * an empty collection; or if this Book has previously
	 * been saved, it will retrieve related Bookincategorys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Book.
	 */
	public function getBookincategorysJoinCategory($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBookincategorys === null) {
			if ($this->isNew()) {
				$this->collBookincategorys = array();
			} else {

				$criteria->add(BookincategoryPeer::ISBN10, $this->isbn10);

				$this->collBookincategorys = BookincategoryPeer::doSelectJoinCategory($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(BookincategoryPeer::ISBN10, $this->isbn10);

			if (!isset($this->lastBookincategoryCriteria) || !$this->lastBookincategoryCriteria->equals($criteria)) {
				$this->collBookincategorys = BookincategoryPeer::doSelectJoinCategory($criteria, $con, $join_behavior);
			}
		}
		$this->lastBookincategoryCriteria = $criteria;

		return $this->collBookincategorys;
	}

	/**
	 * Clears out the collWishlists collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addWishlists()
	 */
	public function clearWishlists()
	{
		$this->collWishlists = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collWishlists collection (array).
	 *
	 * By default this just sets the collWishlists collection to an empty array (like clearcollWishlists());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initWishlists()
	{
		$this->collWishlists = array();
	}

	/**
	 * Gets an array of Wishlist objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Book has previously been saved, it will retrieve
	 * related Wishlists from storage. If this Book is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Wishlist[]
	 * @throws     PropelException
	 */
	public function getWishlists($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collWishlists === null) {
			if ($this->isNew()) {
			   $this->collWishlists = array();
			} else {

				$criteria->add(WishlistPeer::ISBN10, $this->isbn10);

				WishlistPeer::addSelectColumns($criteria);
				$this->collWishlists = WishlistPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(WishlistPeer::ISBN10, $this->isbn10);

				WishlistPeer::addSelectColumns($criteria);
				if (!isset($this->lastWishlistCriteria) || !$this->lastWishlistCriteria->equals($criteria)) {
					$this->collWishlists = WishlistPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastWishlistCriteria = $criteria;
		return $this->collWishlists;
	}

	/**
	 * Returns the number of related Wishlist objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Wishlist objects.
	 * @throws     PropelException
	 */
	public function countWishlists(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collWishlists === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(WishlistPeer::ISBN10, $this->isbn10);

				$count = WishlistPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(WishlistPeer::ISBN10, $this->isbn10);

				if (!isset($this->lastWishlistCriteria) || !$this->lastWishlistCriteria->equals($criteria)) {
					$count = WishlistPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collWishlists);
				}
			} else {
				$count = count($this->collWishlists);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Wishlist object to this object
	 * through the Wishlist foreign key attribute.
	 *
	 * @param      Wishlist $l Wishlist
	 * @return     void
	 * @throws     PropelException
	 */
	public function addWishlist(Wishlist $l)
	{
		if ($this->collWishlists === null) {
			$this->initWishlists();
		}
		if (!in_array($l, $this->collWishlists, true)) { // only add it if the **same** object is not already associated
			array_push($this->collWishlists, $l);
			$l->setBook($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Book is new, it will return
	 * an empty collection; or if this Book has previously
	 * been saved, it will retrieve related Wishlists from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Book.
	 */
	public function getWishlistsJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collWishlists === null) {
			if ($this->isNew()) {
				$this->collWishlists = array();
			} else {

				$criteria->add(WishlistPeer::ISBN10, $this->isbn10);

				$this->collWishlists = WishlistPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(WishlistPeer::ISBN10, $this->isbn10);

			if (!isset($this->lastWishlistCriteria) || !$this->lastWishlistCriteria->equals($criteria)) {
				$this->collWishlists = WishlistPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastWishlistCriteria = $criteria;

		return $this->collWishlists;
	}

	/**
	 * Clears out the collCourselitteratures collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCourselitteratures()
	 */
	public function clearCourselitteratures()
	{
		$this->collCourselitteratures = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCourselitteratures collection (array).
	 *
	 * By default this just sets the collCourselitteratures collection to an empty array (like clearcollCourselitteratures());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCourselitteratures()
	{
		$this->collCourselitteratures = array();
	}

	/**
	 * Gets an array of Courselitterature objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Book has previously been saved, it will retrieve
	 * related Courselitteratures from storage. If this Book is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Courselitterature[]
	 * @throws     PropelException
	 */
	public function getCourselitteratures($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCourselitteratures === null) {
			if ($this->isNew()) {
			   $this->collCourselitteratures = array();
			} else {

				$criteria->add(CourselitteraturePeer::ISBN10, $this->isbn10);

				CourselitteraturePeer::addSelectColumns($criteria);
				$this->collCourselitteratures = CourselitteraturePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CourselitteraturePeer::ISBN10, $this->isbn10);

				CourselitteraturePeer::addSelectColumns($criteria);
				if (!isset($this->lastCourselitteratureCriteria) || !$this->lastCourselitteratureCriteria->equals($criteria)) {
					$this->collCourselitteratures = CourselitteraturePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCourselitteratureCriteria = $criteria;
		return $this->collCourselitteratures;
	}

	/**
	 * Returns the number of related Courselitterature objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Courselitterature objects.
	 * @throws     PropelException
	 */
	public function countCourselitteratures(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCourselitteratures === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CourselitteraturePeer::ISBN10, $this->isbn10);

				$count = CourselitteraturePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CourselitteraturePeer::ISBN10, $this->isbn10);

				if (!isset($this->lastCourselitteratureCriteria) || !$this->lastCourselitteratureCriteria->equals($criteria)) {
					$count = CourselitteraturePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCourselitteratures);
				}
			} else {
				$count = count($this->collCourselitteratures);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Courselitterature object to this object
	 * through the Courselitterature foreign key attribute.
	 *
	 * @param      Courselitterature $l Courselitterature
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCourselitterature(Courselitterature $l)
	{
		if ($this->collCourselitteratures === null) {
			$this->initCourselitteratures();
		}
		if (!in_array($l, $this->collCourselitteratures, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCourselitteratures, $l);
			$l->setBook($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Book is new, it will return
	 * an empty collection; or if this Book has previously
	 * been saved, it will retrieve related Courselitteratures from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Book.
	 */
	public function getCourselitteraturesJoinCourses($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BookPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCourselitteratures === null) {
			if ($this->isNew()) {
				$this->collCourselitteratures = array();
			} else {

				$criteria->add(CourselitteraturePeer::ISBN10, $this->isbn10);

				$this->collCourselitteratures = CourselitteraturePeer::doSelectJoinCourses($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CourselitteraturePeer::ISBN10, $this->isbn10);

			if (!isset($this->lastCourselitteratureCriteria) || !$this->lastCourselitteratureCriteria->equals($criteria)) {
				$this->collCourselitteratures = CourselitteraturePeer::doSelectJoinCourses($criteria, $con, $join_behavior);
			}
		}
		$this->lastCourselitteratureCriteria = $criteria;

		return $this->collCourselitteratures;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAuthors) {
				foreach ((array) $this->collAuthors as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collBooksforsales) {
				foreach ((array) $this->collBooksforsales as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collComments) {
				foreach ((array) $this->collComments as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRatings) {
				foreach ((array) $this->collRatings as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSaless) {
				foreach ((array) $this->collSaless as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collBookincategorys) {
				foreach ((array) $this->collBookincategorys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collWishlists) {
				foreach ((array) $this->collWishlists as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCourselitteratures) {
				foreach ((array) $this->collCourselitteratures as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAuthors = null;
		$this->collBooksforsales = null;
		$this->collComments = null;
		$this->collRatings = null;
		$this->collSaless = null;
		$this->collBookincategorys = null;
		$this->collWishlists = null;
		$this->collCourselitteratures = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseBook:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseBook::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseBook
